parameters:
    # Adds a fallback DATABASE_URL if the env var is not set.
    # This allows you to run cache:warmup even if your
    # environment variables are not available yet.
    # You should not need to change this value.
    env(DATABASE_URL): ''

doctrine:
    dbal:
        # configure these for your database server
        default_connection: default
        connections:
             # A collection of different named connections (e.g. default, conn2, etc)
            default:
                #dbname:               "%database_name%"
                #host:                 "%database_host%"
                #port:                 "%database_port%"
                #user:                 "%database_user%"
                #password:             "%database_password%"
                # charset of the database
                #charset:              utf8mb4
                charset:              UTF8
                # charset and collation of the tables. Not inherited from database
                #default_table_options:
                    #charset:          utf8mb4
                    #collate:          utf8mb4_unicode_ci
                #path:                 ~
                #memory:               ~
                # The unix socket to use for MySQL
                #unix_socket:          ~
                # True to use as persistent connection for the ibm_db2 driver
                #persistent:           ~
                # The protocol to use for the ibm_db2 driver (default to TCPIP if omitted)
                #protocol:             ~
                # True to use dbname as service name instead of SID for Oracle
                #service:              ~
                # The session mode to use for the oci8 driver
                #sessionMode:          ~
                # True to use a pooled server with the oci8 driver
                #pooled:               ~
                # Configuring MultipleActiveResultSets for the pdo_sqlsrv driver
                #MultipleActiveResultSets:  ~
                #driver:               pdo_mysql
                driver:               pdo_pgsql
                #driver_class:         '@App\DBAL\SymfonyPostgresDriver'
                #options:
                    #search_path: symfony
                #platform_service:     ~
                # the version of your database engine
                server_version:       '5.7'
                # if the url option is specified, it will override the above config
                #specified in .env file via dotenv Component
                url: '%env(resolve:DATABASE_URL)%'
                # when true, queries are logged to a 'doctrine' monolog channel
                #logging:              '%kernel.debug%'
                #profiling:            '%kernel.debug%'
                #driver_class:         ~
                #wrapper_class:        ~
                # the DBAL keepSlave option
                #keep_slave:           false
                #options:
                    # an array of options
                #    key:                  []
                #mapping_types:
                    # an array of mapping types
                #    name:                 []

    orm:
        default_entity_manager:  default
        auto_generate_proxy_classes: '%kernel.debug%'
        #mappings:
        #    App:
        #        is_bundle: false
        #        type: annotation
        #        dir: '%kernel.project_dir%/src/Entity'
        #        prefix: 'App\Entity'
        #        alias: App
        entity_managers:
            default:
                connection: default
                # Allow underscore naming strategy ie: $firstName var in Entity file will become first_name in Database column name
                naming_strategy: doctrine.orm.naming_strategy.underscore
                auto_mapping: true
                filters:
                    softdeleteable:
                        class: Gedmo\SoftDeleteable\Filter\SoftDeleteableFilter
                        enabled: true
                mappings:
                    App:
                        is_bundle: false
                        type: annotation
                        dir: '%kernel.project_dir%/src/Entity'
                        prefix: 'App\Entity'
                        alias: App
                    #gedmo_translatable:
                    #    type: annotation
                    #    prefix: Gedmo\Translatable\Entity
                    #    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translatable/Entity"
                    #    alias: GedmoTranslatable # (optional) it will default to the name set for the mapping
                    #    is_bundle: false
                    #gedmo_translator:
                    #    type: annotation
                    #    prefix: Gedmo\Translator\Entity
                    #    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Translator/Entity"
                    #    alias: GedmoTranslator # (optional) it will default to the name set for the mapping
                    #    is_bundle: false
                    gedmo_loggable:
                        type: annotation
                        prefix: Gedmo\Loggable\Entity
                        dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Loggable/Entity"
                        alias: GedmoLoggable # (optional) it will default to the name set for the mappingmapping
                        is_bundle: false
                    #gedmo_tree:
                    #    type: annotation
                    #    prefix: Gedmo\Tree\Entity
                    #    dir: "%kernel.root_dir%/../vendor/gedmo/doctrine-extensions/lib/Gedmo/Tree/Entity"
                    #    alias: GedmoTree # (optional) it will default to the name set for the mapping
                    #    is_bundle: false

