swiftmailer:
    #url: '%env(MAILER_URL)%'
    transport:  "%env(smtp_transport)%"
    host:       "%env(smtp_host)%"
    username:   "%env(smtp_user)%"
    password:   "%env(smtp_password)%"
    port:       "%env(smtp_port)%"
    encryption: "%env(smtp_encrypt)%"
    spool:      { type: memory }
